### PR TITLE
Major refactoring and fixes

### PR DESCRIPTION
**Pull request by jgriffiths**
Hi Dominik,

This pull request is a large set of changes.  It fixes issues #1, #2, #3, #7, #11, #13, #14, #15, #16 and #17 plus a number of bugs without issues, adds a number of new features  and simplifies both the UI and the source code. The app is for me now very usable/useful.

I am intending to make further changes in the future but I thought I would get your comments on the changes so far. If you are happy to pull then I will update the issues on your branch so they can be closed, before starting on the next set of changes.

Please let me know what you think.

Regards
Jon

### CODE REVIEW

**Comment by dschuermann** [comment]
Awesome work! Great to see someone picking up the development where I stopped.
Actually I don't have any specific comments. The pull request looks good.
You could move the icons into the "mipmap" folder as now preferred for launcher icons.

Until now I haven't released this app but it was requested fairly often by users of Offline Calendar. When you are confident that it works good enough we could released it to Google Play under my Sufficiently Secure account and to F-Droid.
If that's okay I can also move it to the SufficientlySecure github project and give you full git access.
Does this sound reasonable?

**Comment by dschuermann** [comment]
@jgriffiths I moved it to SufficientlySecure github project.

**Comment by Gitoffthelawn** [comment]
Looking forward to release.  Perhaps also publish on F-Droid.

**Comment by jgriffiths** [comment]
Hi,

> You could move the icons into the "mipmap" folder 

Sure, I'll have a look at this.

> If that's okay I can also move it to the SufficientlySecure github project and give you full git access. Does this sound reasonable?

That sounds great. I agree that it would be good to get this released. It won't be long before I'd be happy with distributing it I think. 

Regards
Jon

**Pull request merged**
